# Generated by Django 5.1.4 on 2024-12-05 18:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bioapi", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="photos",
            field=models.ManyToManyField(to="bioapi.photo"),
        ),
        migrations.AlterField(
            model_name="album",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 12, 5, 19, 58, 6, 880581)
            ),
        ),
    ]
