# Generated by Django 5.1.4 on 2024-12-05 18:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bioapi", "0002_album_photos_alter_album_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="pub_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
